# Faça um programa que leia um número inteiro qualquer e mostre na tela a sua tabuada.

number = int(input('Type a number: '))
print('=-' * 15)
print(f'{number} x {0:2} = {number * 0}')
print(f'{number} x {1:2} = {number * 1}')
print(f'{number} x {2:2} = {number * 2}')
print(f'{number} x {3:2} = {number * 3}')
print(f'{number} x {4:2} = {number * 4}')
print(f'{number} x {5:2} = {number * 5}')
print(f'{number} x {6:2} = {number * 6}')
print(f'{number} x {7:2} = {number * 7}')
print(f'{number} x {8:2} = {number * 8}')
print(f'{number} x {9:2} = {number * 9}')
print(f'{number} x {10:2} = {number * 10}')
print('=-' * 15)
