# Escreva um programa que leia um valor em metros e o exiba convertido em centímetros e milímetros.

meters = float(input('Type a distance: [meters] '))
kilometers = (meters / 1000)
hectometers = (meters / 100)
decameters = (meters / 10)
decimeters = (meters * 10)
centimeters = (meters * 100)
milimeters = (meters * 1000)
print(f'A distance of {meters} meters is worth: ')
print(f'{kilometers} kilometers')
print(f'{hectometers} hectometers')
print(f'{decameters} decameters')
print(f'{decimeters} decimeters')
print(f'{centimeters} centimeters')
print(f'{milimeters} milimeters')
